# Generated by Django 2.2.7 on 2019-11-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kitchen', models.CharField(max_length=200)),
                ('review_count', models.IntegerField()),
                ('average_delivery_time', models.CharField(max_length=200)),
                ('delivery_cost', models.CharField(max_length=200)),
                ('minimum_order', models.CharField(max_length=200)),
                ('rating_number', models.FloatField(max_length=200)),
            ],
        ),
    ]
